name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test
      - name: Build Docker image
        run: docker build -t my-app:${{ github.sha }} .

  publish-dockerhub:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "ibkwilly" --password-stdin
      - name: Push to Docker Hub
        run: |
          docker tag my-app:${{ github.sha }} ibkwilly/my-app:latest
          docker push ibkwilly/my-app:latest
